config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)
  

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  devise_for :vendors, controllers: {sessions: 'vendors/sessions'}
  
  root 'welcome#index'
  get 'about-us' => 'welcome#about_us', as: "about_us"
  get 'contact-us' => 'welcome#contact_us', as: "contact_us"
  get 'work-with-us' => 'vendor_requests#new', as: "create_vendor_request"
  post 'work-with-us' => 'vendor_requests#create', as: "save_vendor_request"
  get 'hotel-detail/:id' => 'rooms#hotels_detail', as: "hotels_detail"
  get 'search-listing' => 'rooms#search_listing', as: "search_listing"
  get 'account-setting' => 'users#account_setting', as: "account_setting"
  post 'account-setting' => 'users#update_profile', as: "update_profile"
  get 'booking-history' => 'users#booking_history', as: "booking_history"
  get 'confirm-booking/:id' => 'rooms#confirm_booking', as: "confirm_booking"
  post 'save_like'               => 'rooms#save_like', as: 'save_like' 
  post 'check_save_like'         => 'rooms#check_save_like', as: 'check_save_like' 
  post 'review_submit'         => 'rooms#review_submit', as: 'review_submit' 
  post 'discount_offers'         => 'rooms#discount_offers', as: 'discount_offers' 
  post 'booking'         => 'rooms#booking', as: 'booking' 
  post 'check_availability'         => 'rooms#check_availability', as: 'check_availability' 
   
 

  namespace :backend do
    get 'dashboard' => 'dashboard#index', as: "dashboard"
    get 'login' => 'login#login', as: "login"
    get 'overview' => 'dashboard#overview', as: "overview"
    get 'booking' => 'dashboard#booking', as: "booking"
    get 'check-in' => 'dashboard#check_in', as: "check_in"
    get 'check-out' => 'dashboard#check_out', as: "check_out"
    get 'room-list' => 'dashboard#roomlist', as: "roomlist"
    get 'account-setting' => 'dashboard#account_setting', as: "account_setting"
    get 'forgot-password' => 'login#forgot_password', as: "forgot_password"
    get 'otp' => 'login#otp', as: "otp"
  end

  namespace :user do
    get 'dashboard' => 'dashboard#index', as: "dashboard"
  end  

  namespace :admin do
    get 'accept_vendor_request' => 'vendor_requests#accept_vendor_request'
    get 'reject_vendor_request' => 'vendor_requests#reject_vendor_request'
  end

end

app/views/elements/_footer.html.erb
<footer class=" hidden-xs">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-12 footer-logo">
                <%= link_to ('<img src="/assets/footer-logo.png" class="img-responsive" alt="StayHook">').html_safe, root_path %>
            </div>
            <div class="col-md-7 col-sm-7 col-xs-12 text-center foot-link">
                <ul>
                    <li><%= link_to "Home", root_path %></li>
                    <li><a href="explore.html">Explore</a></li>
                    <li><%= link_to "About Us", about_us_path %></li>
                    <li><%= link_to "Contact Us", contact_us_path %></li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
                <div class="follow-home"> 
                    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a> <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a> <a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a> 
                </div>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="foot-stock">
                </div>
            </div>
            <div class="col-md-7 col-sm-6 col-xs-12 copy-txt"> 
                StayHook<sup>&reg;</sup> is a registered Trademark of StayHook Pvt Ltd (ACN 698 425 354)<br>
                Copyright &copy; 2016 StayHook.com (ACN 267 668 173) 
            </div>
            <div class="col-md-5 col-sm-6 col-xs-12">
                <div class="foot-privacy text-uppercase"> 
                    <a href="privacy-policy.html">Privacy Policy</a> <a href="terms-conditions.html">Terms and Conditions</a> 
                </div>
            </div>
        </div>
    </div>
</footer>

<div class="container text-center hidden-sm hidden-md hidden-lg">
    <div class="row">
        <div class="col-lg-12">
            <a href="#top-scroll-head" class="scroll top-g" onClick="return false"><img src="/assets/top-go.png" alt="">BACK TO TOP</a>
            <div class="temss">
                <ul>
                    <li><a href="#">FAQS</a></li>
                    <li><a href="#">PRIVACY POLICY</a></li>
                    <li><a href="#">TERMS & CONDITIONS</a></li>
                </ul>
                <p>© 2016 STAYHOOK PVT LTD. ALL RIGHTS RESERVED.</p>
            </div>
        </div>
    </div>
</div>

app/views/elements/_footer1.html.erb
        <div class="right-footer-sec">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-3">
                <div class="footer-logo"><img src="images/inner-logo.png" class="img-responsive" alt=""></div>
              </div>
              <div class="col-md-6">
                <div class="cent-footer">
                  <p>STAYHOOK ® is a registered Trademark of StayHook Pvt Ltd (ACN 698 425 354)</p>
                  <ul>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Terms and Conditions</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-3">
                <div class="footer-social"> <a href="#"><i class="fa fa-fw" aria-hidden="true" title="Copy to use twitter"></i></a> <a href="#"><i class="fa fa-fw" aria-hidden="true" title="Copy to use facebook-f"></i></a> <a href="#"><i class="fa fa-fw" aria-hidden="true" title="Copy to use google-plus"></i></a> </div>
              </div>
            </div>
          </div>
        </div>

app/views/elements/_header.html.erb
<!--Login page start-->
<% #if !user_signed_in? %>
<div class="modal fade login" id="login" role="dialog">
    <div class="modal-dialog">
        <div class="login-secton">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h5 class="box-titl">Sign In</h5>
             <div class="col-md-12 signin-alert err-msg padding text-center"></div>
            <%= form_for(resource, :as => resource_name, :html => {:id => 'log_in_form_popup'}, :url => user_session_path, :remote => :true, :format => :json) do |f| %>
                <div class="form-group">
                    <label>Your Email ID</label>
                    <%= f.email_field :email, :autofocus => true, :placeholder => "email", :id => 'login_email', class:"form-control", :type => 'email' %>
                </div>
                <div class="form-group">
                    <label>Password</label>
                  
                    <%= f.password_field :password, :placeholder => "password", :id => 'login_password', class:"form-control" %>
                </div>
                <div class="form-group"> 
                    <span class="remb">
                    <%= f.check_box :remember_me %>
               
                        <b>Keep me signed in <a href="#" class="pull-right">Forgot Password</a></b> 
                    </span> 
                </div>
                <div class="form-group">
                <%= f.submit "Sign In", class: "submit-button" %>
                   
                </div>
                <% end %>
                <div class="or-section"> 
                    <b>OR</b> 
                </div>
                <a href="#" class="otp">Login with OTP</a>
        </div>
        <div class="sibn-up"> 
            Not Registered? 
            <a href="#" onClick="return false" data-toggle="modal" data-target="#register" data-dismiss="modal">Sign Up</a> 
        </div>
    </div>
</div>

<% #end %>   

<!--Login page end--> 

<!--Register page start-->
<div class="modal fade" id="register" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="login-secton">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h5 class="box-titl">Create Account</h5>
            <%= form_for(resource, :as => resource_name, :html => {:id => 'signup_form_popup'}, :url => user_registration_path(resource_name), :remote => :true, :format => :json) do |f| %>


                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>FULLname</label>
                            <%= f.text_field :first_name, :autofocus => true, :placeholder => "Tom", :id => 'login_name', class:"form-control", :type => 'text' %>
                            <span class="error" id="error_first_name"></span>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Your E-mail</label>
                            <%= f.email_field :email, :autofocus => true, :placeholder => "name@mail.com", :id => 'login_email', class:"form-control", :type => 'email' %>
                            <span class="error" id="error_email"></span>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>MOBILE NUMBER</label>
                            <%= f.text_field :phone_number, :autofocus => true, :placeholder => "9871234560", :id => 'login_mobile', class:"form-control", :type => 'text' %>
                            <span class="error" id="error_phone_number"></span>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Create Password</label>
                            <%= f.password_field :password, :autofocus => true, :id => 'login_password', class:"form-control", :type => 'password' %>
                            <span class="error" id="error_password"></span>
                        </div>
                    </div>
                </div>
                <p class="terms-cond">By signing up you agree our <a href="#">Terms</a> and <a href="#">Privacy Policy</a></p>
                <div class="form-group fix-width-button">
                 <%= f.submit "Sign up", class: "submit-button" %>
                    
                </div>
                <div class="or-section">
                    <b>OR</b> 
                </div>
                <div class="back-to-login">
                    <i>Already have a StayHook account?</i>
                    <a href="#" onClick="return false" data-toggle="modal" data-target="#login" data-dismiss="modal" class="otp">Log In</a> 
                </div>
            <% end %>
        </div>
    </div>
</div>
<!--Register page end--> 

<header class="cp_header">
    <div id="cp-slide-menu" class="cp_side-navigation">
        <div class="inner-over-div">
            <ul class="sldi-lgoo">
                <li class="nav-bdr" id="close">
                    <img src="/assets/close-mark.png" width="30" alt="">
                </li>
                <li class="nav-logo">
                    <center>
                      <img src="/assets/nav-logo.png" class="img-responsive" alt="StayHook">
                    </center>
                </li>
                <li class="search-product">
                    <img src="/assets/search-icon.png" width="30" alt="">
                </li>
            </ul>
            <ul class="navbar-nav">
                <li><a href="" class="homebdr">
                    Home</a>
                </li>
                <li>
                    <%= link_to "Work With US", create_vendor_request_path %>
                </li>
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Explore StayHook <i class="fa fa-angle-down fa-lg" aria-hidden="true"></i></a> 
                    <ul class="dropdown-menu">
                        <li><a href="blog.html">Blog</a></li>
                        <li><a href="booking-gurantee.html">Booking Gurantee</a></li>
                    </ul>
                </li>
                <% if user_signed_in? %> 
                    <li>
                        <%= link_to('<i class="signup  hidden-xs">Sign Out</i>'.html_safe, destroy_user_session_path, :method => :get) %>
                    </li>
                <% else %>
                    <li>
                        <a href="#" onClick="return false" data-toggle="modal" class="signin  hidden-xs" data-target="#login">Sign In</a>
                        <a class="signup" href="#" onClick="return false" data-toggle="modal" data-target="#register">Sign Up</a> <em class="sarch-top-meu  hidden-lg  hidden-md  hidden-sm"></em>
                    </li>
                <% end %>
                <li><a href="help.html" class="helpbdr">Help</a></li>
            </ul>
            <div class="social-icons"> 
                <a href="#"><img src="/assets/soicla-1.png" width="30" height="29" alt=""></a> <a href="#"><img src="/assets/soicla-2.png" width="30" height="29" alt=""></a> <a href="#"><img src="/assets/soicla-3.png" width="30" height="29" alt=""></a> 
            </div>
        </div>
    </div>
    <div class="cp-navigation-row">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2 col-sm-2 col-xs-2">
                    <div class="cp-nav-holder">
                        <div id="push" class="cp-sidemenu">
                            <a onClick="return false" href="#"><i class="fa fa-fw" aria-hidden="true" title="Copy to use bars"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-8 col-sm-6 col-xs-8 text-center">
                    <div class="logo">
                        <%= link_to"", root_path %>
                    </div>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-2 text-right loginwrap"> 
                    <% if user_signed_in? %> 
                        
                    <div class="after-login-user">
                        <div class="user-da-down">
                                <button class="" type="button" data-toggle="dropdown">
                                    <em>
                                    <% if current_user.image.present? %>
                                        <img src="<%= current_user.image.thumb.url %>" width="35" class="img-circle" alt="">
                                    <% else %>
                                       <img src="/assets/dashboard-user.jpg" width="35" class="img-circle" alt="">
                                    <% end %>
                                    </em>
                                    <i class="hidden-xs">
                                        Hi, <%= current_user.first_name %>
                                    </i> 
                                    <span class="down-aro"></span>
                                </button>
                            <ul class="dropdown-menu">
                                <li><%= link_to('Account Settings', account_setting_path) %></li>
                                <li><%= link_to('Booking History', booking_history_path) %></li>
                                <li><a href="#">Refer A Friend</a></li>
                                <li><%= link_to('Log Out', destroy_user_session_path, :method => :get) %></li>
                            </ul>
                        </div>
                    </div>
                
                    <% else %>
                        <a href="#" onClick="return false" data-toggle="modal" class="signin  hidden-xs" data-target="#login">Sign In</a>
                        <a class="signup" href="#" onClick="return false" data-toggle="modal" data-target="#register">Sign Up</a> <em class="sarch-top-meu  hidden-lg  hidden-md  hidden-sm"></em>
                    <% end %>   
                </div>
            </div>
        </div>
    </div>
</header>

<script type="text/javascript">
                
    $(document).on('submit', '#log_in_form_popup', function(e) {
        
        //do stuff here
    }).on('ajax:success', '#log_in_form_popup', function(e, data, status, xhr) {
        if(status == 'success'){
            window.location.href = '<%= root_path %>';
        }else{
            $('.signin-alert').html('Invalid email or password!');
            $('.signin-alert').show();
        }
    
    }).on('ajax:error', '#log_in_form_popup', function(e, data, status, xhr) {
       
        msg = 'Invalid email or password!';

        if (data['responseText'] == 'UserInactive'){
            msg = 'Sorry, this account is deactivated!';
        }

        $('.signin-alert').html(msg);
        $('.signin-alert').show();
        
    });
    
    $(document).ready(function(){
        
        $('#login-popup-link').click(function(){
            $('.signin-alert').html('');
            $('.signin-alert').hide();
        });
    });


    $(document).on('submit', '#signup_form_popup', function(e) {

        $(".error").html('');

    }).on('ajax:success', '#signup_form_popup', function(e, data, status, xhr) {
        //alert(2);

        //alert(JSON.stringify(e));
        if((data['success']) === true){
          
            window.location.href = '<%= root_path %>';
            
        }else{

            $.each(data['errors'], function( index, value ) {
              //alert(JSON.stringify(index));
              $("#error_" + index).html(value[0]);
              //alert(JSON.stringify(value));
            });

                //for (i = 0; i < data['errors'].length; i++) {
               //var text += data['errors'][i] + "<br>";
             //   alert(data['errors']);
           // }


        }
       // alert((JSON.stringify(data['errors'])));
        
       // alert(JSON.stringify(status));
       // alert(JSON.stringify(xhr));

    }).on('ajax:error', '#signup_form_popup', function(e, data, status, xhr) {
        alert(3);
        //alert(JSON.stringify(e));
       // alert(JSON.stringify(data));
       // alert(JSON.stringify(status));
       // alert(JSON.stringify(xhr));
        
    });

    
    $(document).ready(function(){
        
        $('#signup-popup-link').click(function(){
            $('.signin-alert').html('');
            $('.signin-alert').hide();
        });
    });
</script>

app/views/elements/_header1.html.erb
<div id="cp-slide-menu" class="cp_side-navigation">
    <div class="inner-over-div">
        <ul class="sldi-lgoo">
            <li class="nav-bdr" id="close"><img src="/assets/close-mark.png" width="30" alt=""></li>
            <li class="nav-logo">
                <center>
                  <img src="/assets/nav-logo.png" class="img-responsive" alt="StayHook">
                </center>
            </li>
            <li class="search-product"><img src="/assets/search-icon.png" width="30" alt=""></li>
        </ul>
        <ul class="navbar-nav">
            <li><a href="index.html" class="homebdr">Home</a></li>
            <li><a href="signup-host.html">Work With US</a></li>
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Explore StayHook <i class="fa fa-angle-down fa-lg" aria-hidden="true"></i></a>
            <ul class="dropdown-menu">
                <li><a href="blog.html">Blog</a></li>
                <li><a href="booking-gurantee.html">Booking Gurantee</a></li>
            </ul>
        </ul>
            <li><a href="#" onClick="return false" data-toggle="modal" data-target="#login">Sign In</a></li>
            <li><a href="#" onClick="return false" data-toggle="modal" data-target="#register">Sign Up</a></li>
            <li><a href="help.html" class="helpbdr">Help</a></li>
    
        <div class="social-icons"> 
            <a href="#"><img src="/assets/soicla-1.png" width="30" height="29" alt=""></a> <a href="#"><img src="/assets/soicla-2.png" width="30" height="29" alt=""></a> <a href="#"><img src="/assets/soicla-3.png" width="30" height="29" alt=""></a> 
        </div>
    </div>
</div>
 
    <!-- Search Header -->
    <section class="SearchHeader clearfix hidden-xs">
        <div class="Searchlogo"> 
            <a class="in-menus" onclick="return false" href="#"><i class="fa fa-fw" aria-hidden="true" title="Copy to use bars"></i></a>
                <%= link_to ('<center>
                    <img src="/assets/nav-logo.png" class="img-responsive" alt="StayHook">
                </center>').html_safe, root_path %>
        </div>
        
        <div class="SearchHeaderRight">
            <div class="pull-left TopSearch">
                <input class="form-control" placeholder="Search" type="text">
            </div>
            <% if user_signed_in? %>
            <div class="pull-right SearchProfile dropdown"> <span class="hidden-xs"><%= current_user.first_name %></span>
                <div class="profile-search"> 
                     <img src="<%= current_user.image.thumb.url %>" class="img-responsive img-circle" alt="Profile">
                </div>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-angle-down fa-lg" aria-hidden="true"></i></a>
                <ul class="dropdown-menu">
                    <li><a href="account-setting">Account Settings</a></li>
                    <li><a href="booking-history">Booking History</a></li>
                    <li><a href="#">Refer A Friend</a></li>
                    <li><%= link_to('Log Out', destroy_user_session_path, :method => :get) %></li>
                </ul>
            </div>
            <% end %>
        </div>
        
    </section>
    <header class="cp_header mobile-scertn hidden-sm hidden-md hidden-lg">
        <div id="cp-slide-menu" class="cp_side-navigation"> </div>
        <div class="cp-navigation-row">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-2 col-sm-2 col-xs-2">
                        <div class="cp-nav-holder">
                            <div id="push" class="cp-sidemenu">
                                <a onclick="return false" href="#"><i class="fa fa-fw" aria-hidden="true" title="Copy to use bars"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8 col-sm-6 col-xs-8 text-center">
                        <div class="logo"><a href="index.html"></a></div>
                    </div>
                    <div class="col-md-2 col-sm-4 col-xs-2 text-right loginwrap"> 
                        <a href="#" onclick="return false" data-toggle="modal" class="signin  hidden-xs" data-target="#login">Sign In</a> <a class="signup" href="#" onclick="return false" data-toggle="modal" data-target="#register">Sign Up</a> <em class="sarch-top-meu search-product  hidden-lg  hidden-md  hidden-sm"></em> 
                    </div>
                </div>
            </div>
        </div>
    </header>

app/views/elements/_header2.html.erb
<header class="cp_header">
    <div id="cp-slide-menu" class="cp_side-navigation">
        <ul class="navbar-nav">
            <li class="nav-bdr" id="close"><a href="#"><i class="fa fa-close"></i></a></li>
                <li class="nav-logo">
                  <center>
                    <img src="/assets/nav-logo.png" class="img-responsive" alt="StayHook">
                  </center>
                </li>
                <li><a href="index.html" class="homebdr">Home</a></li>
                <li><a href="explore.html">Work With US</a></li>
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Explore StayHook <i class="fa fa-angle-down fa-lg" aria-hidden="true"></i></a>
                  <ul class="dropdown-menu">
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="booking-gurantee.html">Booking Gurantee</a></li>
                  </ul>
                </li>
                    <li><a href="signn.html">Sign In</a></li>
                <li><a href="signup.html">Sign Up</a></li>
                <li><a href="help.html" class="helpbdr">Help</a></li>
        </ul>
    </div>
    <div class="cp-navigation-row">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-1 col-sm-2 col-xs-2">
                    <div class="cp-nav-holder">
                        <div id="push" class="cp-sidemenu">
                            <a href="#"><img src="/assets/menu-b.jpg" alt="Menu"></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-9 col-sm-6 col-xs-7 text-center">
                    <div class="logo">
                        <a href="index.html"><img src="/assets/inner-logo.png" class="img-responsive" alt="StayHook"></a>
                    </div>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-3 text-right loginwrap">
                    <div class="after-login-user">
                        <div class="user-da-down">
                                <button class="" type="button" data-toggle="dropdown">
                                    <em>
                                    <% if current_user.image.present? %>
                                        <img src="<%= current_user.image.thumb.url %>" width="35" class="img-circle" alt="">
                                    <% else %>
                                       <img src="/assets/dashboard-user.jpg" width="35" class="img-circle" alt="">
                                    <% end %>
                                    </em>
                                    <i class="hidden-xs">
                                        Hi, <%= current_user.first_name %>
                                    </i> 
                                    <span class="down-aro"></span>
                                </button>
                            <ul class="dropdown-menu">
                                <li><a href="account-setting">Account Settings</a></li>
                                <li><a href="booking-history">Booking History</a></li>
                                <li><a href="#">Refer A Friend</a></li>
                                <li><%= link_to('Log Out', destroy_user_session_path, :method => :get) %></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/elements/_left_nav_profileuser.html.erb
<div class="col-md-3">
    <div class="left-muns">
	    <%= form_for(@user, url: update_profile_path, html: { method: :post , :id => "edit_profile_pic_form"}) do |f| %>
	        <div class="user-pics"> 
	            <span class="user-img">
	                <% if current_user.image.present? %>
	                    <img onclick="document.getElementById('user_profile').click()" src="<%= current_user.image.small.url %>" width="120px" class="img-circle img-responsive" alt="">
	                <% else %>
	                    <img onclick="myFunction()" src="/assets/dashboard-user.jpg" width="120px" class="img-circle img-responsive" alt="">
	                <% end %>
	                <%= f.file_field(:image,class: "required", title: " ", onchange: "this.form.submit()", id: "user_profile", style: 'display: none;')%>
	            </span>  <b><%= current_user.first_name %> <%= current_user.last_name %></b> 
	        </div>
	    <% end %>
        <ul>
            <li><a href="booking-history">Booking</a></li>
            <li><a href="account-setting">Profile</a></li>
            <li><%= link_to('Sign Out', destroy_user_session_path, :method => :get) %></li>
        </ul>
    </div>
</div>