config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)
  

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  devise_for :vendors, controllers: {sessions: 'vendors/sessions'}
  
  root 'welcome#index'
  get 'about-us' => 'welcome#about_us', as: "about_us"
  get 'contact-us' => 'welcome#contact_us', as: "contact_us"
  get 'work-with-us' => 'vendor_requests#new', as: "create_vendor_request"
  post 'work-with-us' => 'vendor_requests#create', as: "save_vendor_request"
  get 'hotel-detail/:id' => 'rooms#hotels_detail', as: "hotels_detail"
  get 'search-listing' => 'rooms#search_listing', as: "search_listing"
  get 'account-setting' => 'users#account_setting', as: "account_setting"
  post 'account-setting' => 'users#update_profile', as: "update_profile"
  get 'booking-history' => 'users#booking_history', as: "booking_history"
  get 'confirm-booking/:id' => 'rooms#confirm_booking', as: "confirm_booking"
  post 'save_like'               => 'rooms#save_like', as: 'save_like' 
  post 'check_save_like'         => 'rooms#check_save_like', as: 'check_save_like' 
  post 'review_submit'         => 'rooms#review_submit', as: 'review_submit' 
  post 'discount_offers'         => 'rooms#discount_offers', as: 'discount_offers' 
  post 'booking'         => 'rooms#booking', as: 'booking' 
  post 'check_availability'         => 'rooms#check_availability', as: 'check_availability' 
   
 

  namespace :backend do
    get 'dashboard' => 'dashboard#index', as: "dashboard"
    get 'login' => 'login#login', as: "login"
    get 'overview' => 'dashboard#overview', as: "overview"
    get 'booking' => 'dashboard#booking', as: "booking"
    get 'check-in' => 'dashboard#check_in', as: "check_in"
    get 'check-out' => 'dashboard#check_out', as: "check_out"
    get 'room-list' => 'dashboard#roomlist', as: "roomlist"
    get 'account-setting' => 'dashboard#account_setting', as: "account_setting"
    get 'forgot-password' => 'login#forgot_password', as: "forgot_password"
    get 'otp' => 'login#otp', as: "otp"
  end

  namespace :user do
    get 'dashboard' => 'dashboard#index', as: "dashboard"
  end  

  namespace :admin do
    get 'accept_vendor_request' => 'vendor_requests#accept_vendor_request'
    get 'reject_vendor_request' => 'vendor_requests#reject_vendor_request'
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end

	def about_us

		@aboutpage_detail = StaticPage.find_by(title: 'About Us')
		#abort(@aboutpage_detail.to_json)
	end

	def contact_us
	end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about_us.html.erb
<div class="main-section" id="top-scroll-head"> 
    <!-- Banner Start -->
    <section class="about-banner">
        <div class="container">
            <center>
            <%= link_to ('<img src="/assets/about-logo.png" class="img-responsive" alt="StayHook">').html_safe, root_path %>
            </center>
            <div class="down-aros text-center">
                <a href="#a" onClick="return false" class="scroll">
                    <i class="arrow-down"><img src="/assets/down-arrow.png" alt=""></i>
                </a>
            </div>
        </div>
    </section>

    <!-- Container Start -->
    <section class="aboutwrap clearfix" id="a">
        <div class="container">
            <div class="about-box clearfix">
                <h2>About Us</h2>
                <% if @aboutpage_detail.content.present? %>
                    <%= @aboutpage_detail.content.html_safe %>
                <% end %>
                
            </div>
        </div>
    </section>
</div>


app/views/welcome/contact_us.html.erb
<body class="contact-page">
    <div class="sibn-up-host" id="top-scroll-head">
        <!-- Header Start -->
        <div class="contact-us-secion">
            <div class="container">
                <div class="row">
                    <div class="col-sm-7 col-md-8">
                        <div class="login-secton">     
                            <form>
                                <div class="container-fluid">
                                    <div class="row">
                                        <h5 class="cont-tiel">Contact Us</h5>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Your name</label>
                                                <input class="form-control" type="text">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>your mobile number</label>
                                                <input class="form-control" type="text">
                                            </div>
                                        </div>        
                                        <div class="col-sm-12">
                                            <div class="form-group">
                                                <label>Your Message</label>
                                                <textarea class="form-control"></textarea>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Your E-mail</label>
                                                <input class="form-control" type="text">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="hidden-sm">&nbsp;</label>
                                                <button type="submit" class="submit-button">Send Your message</button>
                                            </div>
                                        </div> 
                                        <div class="col-lg-12">
                                            <span class="attachment">
                                                <i><img src="images/attach.png"  alt=""> ADD ATTACHMENTS</i>
                                                <input type="file">
                                            </span>
                                        </div>  
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-sm-5 col-md-4">
                        <div class="side-assress">
                            <ul>
                                <li>
                                    <i>E-mail</i>
                                    <p>denis@getcraftwork.com</p>
                                </li>
                                <li>
                                    <i>Phone</i>
                                    <p>+30 356 3778 241</p>
                                </li>
                                <li>
                                    <i>Address</i>
                                    <p>San Francisco, CA <br>
                                    560 Bush St & 20th Ave, Apt <br>
                                    5 San Francisco, 230909</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

app/views/welcome/create_vendor_request.html.erb
<div class="sibn-up-host" id="top-scroll-head">
    <div class="banner-image-host text-center">
        <h5 class="box-titl">Sign Up</h5>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. </p>
    </div>

    <div class="container">
        <div class="login-secton">     
            <%= form_for(@vendor_request, url: save_vendor_request_path(@vendor_request), html: { method: :post, :id => "vendor_request" }) do |f| %>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>First Name</label>
                                <%= f.text_field :first_name, autocomplete: "off", class: 'form-control', id: 'first_name', placeholder: 'Enter First Name' %>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Last Name</label>
                                <%= f.text_field :last_name, autocomplete: "off", class: 'form-control', id: 'last_name', placeholder: 'Enter Last Name' %>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>CITY</label>
                                <%= f.select :city_id, options_for_select(City.active.order('name ASC').pluck(:name, :id)), {prompt: 'Select City Name'} %>
                            </div>
                        </div>
                    
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>E-MAIL</label>
                                <%= f.email_field :email, autocomplete: "off", class: 'form-control', id: 'email', placeholder: 'Enter Email' %>
                            </div>
                        </div>
                        
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Phone</label>
                                <%= f.text_field :phone_number, autocomplete: "off", class: 'form-control', id: 'phone_number', placeholder: 'Enter Phone Number' %>
                            </div>
                        </div>
                    
                        <div class="col-sm-4">
                            <div class="form-group address-tex">
                                <label>Address</label>
                                <%= f.text_area :address, autocomplete: "off", class: 'form-control', id: 'address', placeholder: 'Enter Address' %>
                            </div>
                        </div>
                      
                    </div>
                    <hr class="mid-lin">
                    <div class="form-group fix-width-button">
                        <button type="submit" class="submit-button" value="Save" name="commit">Get started</button>
                    </div>
                </div>
            <% end %>   
        </div>
    </div>
</div>

app/views/welcome/index.html.erb



<!--Moblie searching start-->
<div class="mobile-searching text-center">
    <div class="cont-search"> <b class="close-search"><img src="/assets/search-close.png" width="35" alt=""></b>

        <div class="search-fields">
            <div class="select-city">
                <select>
                    <option value="1">Select City</option>
                    <option value="2">Jaipur</option>
                    <option value="3">Ajmer</option>
                    <option value="4">Kota</option>
                    <option value="5">Bikaner</option>
                    <option value="6">Jodhpur</option>
                </select>

            </div>
            <p class="or-s">OR</p>
            <div class="searchhome">
                <input class="form-control" placeholder="Search by locality, address..." type="text">
            </div>
            <div class="check-box-"> <b>CATEGORY</b>
                <ul>
                    <li>
                        <input type="radio" id="king" name="selector">
                        <label for="king" class="king firs-op">King</label>
                    </li>
                    <li>
                        <input type="radio" id="queen" name="selector">
                        <label for="queen" class="king second-op">Queen</label>
                    </li>
                    <li>
                        <input type="radio" id="people" name="selector">
                        <label for="people" class="king third-op">Family</label>
                    </li>
                </ul>
            </div>
            <div class="how-long-box">
                <select>
                    <option value="1">How long?</option>
                    <option value="2">Regular Booking</option>
                    <option value="3">Long-Term Booking</option>
                    
                </select>
            </div>
            <div class="check-box- checkbox-for-room"> 
                <b>ROOM</b>
                <ul>
                    <li>
                        <input type="radio" id="private" name="selector-1">
                        <label for="private" class="king second-op">PRIVATE</label>
                    </li>
                    <li>
                        <input type="radio" id="shared" name="selector-1">
                        <label for="shared" class="king third-op">SHARED</label>
                    </li>
                </ul>
            </div>
            <div class="search-box">
                <button class="search-btn" type="submit">Search</button>
            </div>
        </div>  

    </div>
</div>
<!--Moblie searching start-->

<div class="main-section" id="top-scroll-head"> 
    <!-- Header Start -->

    <!-- Banner Start -->
    <section class="banner clearfix">

<%= form_tag search_listing_path, method: :get do %>
        <div class="container hidden-xs">
            <h1>Search Through Best Hostels &amp; Hotels</h1>
            <ul>
                <li class="clearfix">

                    <div class="citybox clearfix">                        
                        <%= select_tag "filter[city]", options_for_select(City.active.order('name ASC').pluck(:name, :id)), {include_blank: "Select City"} %>
                    </div>

                    <div class="searchhome">
                        <%= text_field_tag "filter[address]", "", placeholder: "Search by locality, address...", class: "form-control" %>
                    </div>

                    <div class="couple-box">
                        <%= select_tag "filter[room_for]", options_for_select(Room::ROOM_FOR), {include_blank: "King / Queen / Family"} %>
                    </div>

                    <div class="duration-box">
                        <select>
                            <option value="1">Duration</option>
                            <option value="2">Regular Booking</option>
                            <option value="3">Long-Term Booking</option>
                        </select>
                    </div>

                    <div class="search-box">
                        <button class="search-btn" type="submit" >
                            <i class="fa fa-search hidden-sm hidden-xs" aria-hidden="true">
                            </i>
                            <span class="hidden-md hidden-lg">Search
                            </span>
                        </button>
                    </div>

                </li>
            </ul>
            <div class="text-center start-txt text-uppercase">
                Starting at Rs 399* only
            </div>
            <div class="down-aros text-center"> 
                <a href="#a" onClick="return false" class="scroll">
                    <i class="arrow-down"><img src="/assets/down-arrow.png" alt=""></i>
                </a> 
            </div>
        </div>

        <div class="container hidden-lg hidden-md hidden-sm">
            <div class="mobile-searchin-sec text-center">
                <h5>Welcome <Br>
                To <Br>
                Stayhook</h5>
                <button type="button" class="show-firm-se">Search 
                    <i class="fa fa-fw" aria-hidden="true" title="Copy to use search">
                    </i>
                </button>
                <div class="text-center start-txt text-uppercase">
                    Hook Your Stays<Br>
                    Starting at? <Br>
                    Just Rs 399* only
                </div>
                <div class="down-aros text-center"> 
                    <a href="#a" onClick="return false" class="scroll">
                        <i class="arrow-down">
                            <img src="/assets/down-arrow.png" alt="">
                        </i>
                    </a> 
                </div>
            </div>
        </div>
<% end %>
    </section>

    <!-- Where to Start -->
    <section class="clearfix wherewrap" id="a">
        <div class="col-md-12 col-sm-12 col-xs-12 hidden-xs">
            <h2>Amazing Experience <i></i></h2>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="row">
                        <div class="ovver-images ofer-img-1">
                            <div class="ove-text-in">
                                <p>ROOMS  FOR <Br>
                                KINGS</p>
                                <a href="<%= search_listing_path %>?filter[room_for]=King">LOOK</a> 
                            </div>
                            <img src="/assets/roomforking-img.jpg" alt="ROOMS  FOR KINGS"> 
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="row">
                        <div class="ovver-images ofer-img-1">
                            <div class="ove-text-in">
                                <p>ROOMS  FOR <Br>
                                QUEENS</p>
                                <a href="<%= search_listing_path %>?filter[room_for]=Queen">LOOK</a> 
                            </div>
                            <img src="/assets/roomforking-img1.jpg" alt="ROOMS  FOR KINGS"> 
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="row">
                        <div class="ovver-images ofer-img-1">
                            <div class="ove-text-in">
                                <p>ROOMS <Br>
                                FOR  COUPLES</p>
                                <a href="">LOOK</a> 
                            </div>
                            <img src="/assets/roomforking-img2.jpg" alt="ROOMS  FOR KINGS"> 
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="row">
                        <div class="ovver-images ofer-img-1">
                            <div class="ove-text-in">
                                <p>ROOMS <Br>
                                FOR  FAMILIES</p>
                                <a href="<%= search_listing_path %>?filter[room_for]=Family">LOOK</a> 
                            </div>
                            <img src="/assets/roomforking-img3.jpg" alt="ROOMS  FOR KINGS"> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Feature Start -->
    <section class="featurewrap clearfix hidden-xs">
        <div class="container">
            <h2>Features</h2>
            <ul>
                <li class="botbdr">
                    <center>
                        <img src="/assets/spacemen-icon.png" alt="Spacemen">
                    </center>
                    <h3>Spacemen</h3>
                    <p>She gave my mother such a turn, that I have always been convinced I am indebted to Miss Betsey for having been born on a Friday.</p>
                </li>
                <li class="botbdr">
                    <center>
                        <img src="/assets/sun-icon.png" alt="Sun">
                    </center>
                        <h3>Sun</h3>
                        <p>It was some time before he obtained any answer, and the reply, when made, was unpropitious.</p>
                </li>
                <li class="botbdr rightbdr">
                    <center>
                        <img src="/assets/time-icon.png" alt="Time">
                    </center>
                    <h3>Time</h3>
                    <p>Thus much I thought proper to tell you in relation to yourself, and to the trust I reposed in you.</p>
                </li>
                <li>
                    <center>
                        <img src="/assets/moon-icon.png" alt="Moon">
                    </center>
                    <h3>Moon</h3>
                    <p>This sounded a very good reason, and Alice was quite pleased to know it. 'I never thought of that before!' she said.</p>
                </li>
                <li>
                    <center>
                        <img src="/assets/wind-icon.png" alt="Wind">
                    </center>
                    <h3>wind</h3>
                    <p>Looking cautiously round, to ascertain that they were not overheard, the two hags cowered nearer to the fire, and chuckled heartily.</p>
                </li>
                <li class="rightbdr">
                    <center>
                        <img src="/assets/radio-icon.png" alt="Radio">
                    </center>
                    <h3>Radio</h3>
                    <p>A hundred thousand grateful loves to your dear papa and mamma.</p>
                </li>
            </ul>
        </div>
    </section>

    <!-- Support Start -->
    <section class="supportwrap clearfix">
        <div class="container">
            <ul>
                <li>
                    <h2>Customer support</h2>
                    <p>If you need help while traveling or hosting, contact us at our toll free number: 00 08004405103</p>
                </li>
                <li>
                    <h2>AMAZING EXPERIENCE</h2>
                    <p>Now the races of these two have been for some ages utterly extinct, and besides to discourse any further of them would not be at all to my purpose.</p>
                </li>
                <li>
                    <h2>vERIFID ID</h2>
                    <p>We aim to build a trusted community by giving you more info when you're deciding who to host or stay with.</p>
                </li>
            </ul>
        </div>
    </section>
</div>
