config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)
  

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  devise_for :vendors, controllers: {sessions: 'vendors/sessions'}
  
  root 'welcome#index'
  get 'about-us' => 'welcome#about_us', as: "about_us"
  get 'contact-us' => 'welcome#contact_us', as: "contact_us"
  get 'work-with-us' => 'vendor_requests#new', as: "create_vendor_request"
  post 'work-with-us' => 'vendor_requests#create', as: "save_vendor_request"
  get 'hotel-detail/:id' => 'rooms#hotels_detail', as: "hotels_detail"
  get 'search-listing' => 'rooms#search_listing', as: "search_listing"
  get 'account-setting' => 'users#account_setting', as: "account_setting"
  post 'account-setting' => 'users#update_profile', as: "update_profile"
  get 'booking-history' => 'users#booking_history', as: "booking_history"
  get 'confirm-booking/:id' => 'rooms#confirm_booking', as: "confirm_booking"
  post 'save_like'               => 'rooms#save_like', as: 'save_like' 
  post 'check_save_like'         => 'rooms#check_save_like', as: 'check_save_like' 
  post 'review_submit'         => 'rooms#review_submit', as: 'review_submit' 
  post 'discount_offers'         => 'rooms#discount_offers', as: 'discount_offers' 
  post 'booking'         => 'rooms#booking', as: 'booking' 
  post 'check_availability'         => 'rooms#check_availability', as: 'check_availability' 
   
 

  namespace :backend do
    get 'dashboard' => 'dashboard#index', as: "dashboard"
    get 'login' => 'login#login', as: "login"
    get 'overview' => 'dashboard#overview', as: "overview"
    get 'booking' => 'dashboard#booking', as: "booking"
    get 'check-in' => 'dashboard#check_in', as: "check_in"
    get 'check-out' => 'dashboard#check_out', as: "check_out"
    get 'room-list' => 'dashboard#roomlist', as: "roomlist"
    get 'account-setting' => 'dashboard#account_setting', as: "account_setting"
    get 'forgot-password' => 'login#forgot_password', as: "forgot_password"
    get 'otp' => 'login#otp', as: "otp"
  end

  namespace :user do
    get 'dashboard' => 'dashboard#index', as: "dashboard"
  end  

  namespace :admin do
    get 'accept_vendor_request' => 'vendor_requests#accept_vendor_request'
    get 'reject_vendor_request' => 'vendor_requests#reject_vendor_request'
  end

end

app/controllers/backend/base_controller.rb
class Backend::BaseController < ApplicationController
	
	
end

app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < Backend::BaseController
	before_action :authenticate_vendor!

	layout 'backend'
	
	def index
		
				
	end
    
	def overview
		
				
	end
	def booking
		
				
	end
	def check_in
		
				
	end
	def check_out
		
				
	end
	def roomlist
		
				
	end
	def account_setting
		
				
	end
	
end

app/controllers/backend/login_controller.rb
class Backend::LoginController < Backend::BaseController

    layout 'backend_login'
	def login
        
	end
	def otp
        
	end
	def forgot_password
        
	end
	
end

app/views/backend/login/forgot_password.html.erb

<div id="main_container">
    <div class="admin_login_section">
        <div class="admin_login_blk">
            <div class="logo_img">
                <img src="/assets/backend/logo-img.png"/>
            </div>
            <form>
                <div class="form-group">
                    <label>Forgot Password</label>
                    <div class="form_content">
                        <input class="form-control" placeholder="9871234567" type="text">
                        <i class="fa fa-user" aria-hidden="true"></i> 
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Send otp">
                </div>
                <span class="otp_txt">OTP Sent to Registered mobile number</span>
            </form>
        </div>
    </div>
</div>


app/views/backend/login/login.html.erb


<div id="main_container">
    <div class="admin_login_section">
        <div class="admin_login_blk">
        
            <div class="logo_img"><img src="/assets/backend/logo-img.png"/></div>
            <div class="col-md-12 signin-alert err-msg text-center"></div>
            <%= form_for(resource, :as => 'vendor', :html => {:id => 'vendor_log_in_form'}, :url => vendor_session_path, :remote => :true, :format => :json) do |f| %>
                <div class="form-group">
                    <div class="form_content">
                        <%= f.email_field :email, :autofocus => true, :placeholder => "Email ID", :id => 'login_email', class:"form-control", :type => 'email' %>
                        <i class="fa fa-user" aria-hidden="true"></i> 
                    </div>
                </div>
                <div class="form-group">
                    <div class="form_content">
                        <%= f.password_field :password, :placeholder => "Password", :id => 'login_password', class:"form-control" %>
                        <i class="fa fa-lock" aria-hidden="true"></i> 
                    </div>
                </div>
                <div class="form-group">
                    <a href="<%= backend_forgot_password_path %>">Forgot <span>Password?</span></a>
                </div>
                <div class="form-group">
                    <%= f.submit "Sign In" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

<script type="text/javascript">
                
    $(document).on('submit', '#vendor_log_in_form', function(e) {
        
        //do stuff here
    }).on('ajax:success', '#vendor_log_in_form', function(e, data, status, xhr) {
        if(status == 'success'){
            window.location.href = '<%= backend_dashboard_path %>';
        }else{
            $('.signin-alert').html('Invalid email or password!');
            alert();
            $('.signin-alert').show();
        }
    
    }).on('ajax:error', '#vendor_log_in_form', function(e, data, status, xhr) {
       
        msg = 'Invalid email or password!';

        if (data['responseText'] == 'UserInactive'){
            msg = 'Sorry, this account is deactivated!';
        }

        $('.signin-alert').html(msg);
        $('.signin-alert').show();
        
    });
    
    $(document).ready(function(){
        
        $('#vendor_log_in_form').click(function(){
            $('.signin-alert').html('');
            $('.signin-alert').hide();
        });
    });
    
</script>

app/views/backend/login/login1.html.erb
<br></br>    
<br></br>    
<div class="col-md-12 signin-alert err-msg padding text-center"></div>
    <%= form_for(resource, :as => 'vendor', :html => {:id => 'vendor_log_in_form'}, :url => vendor_session_path, :remote => :true, :format => :json) do |f| %>
        <div class="form-group">
            <label>Your Email ID</label>
            <%= f.email_field :email, :autofocus => true, :placeholder => "email", :id => 'login_email', class:"form-control", :type => 'email' %>
        </div>
        <div class="form-group">
            <label>Password</label>
          
            <%= f.password_field :password, :placeholder => "password", :id => 'login_password', class:"form-control" %>
        </div>
        <div class="form-group"> 
            <span class="remb">
            <%= f.check_box :remember_me %>
       
                <b>Keep me signed in <a href="#" class="pull-right">Forgot Password</a></b> 
            </span> 
        </div>
        <div class="form-group">
        <%= f.submit "Sign In", class: "submit-button" %>
           
        </div>
    <% end %>
</div>


<script type="text/javascript">
                
    $(document).on('submit', '#vendor_log_in_form', function(e) {
        
        //do stuff here
    }).on('ajax:success', '#vendor_log_in_form', function(e, data, status, xhr) {
        if(status == 'success'){
            window.location.href = '<%= backend_dashboard_path %>';
        }else{
            $('.signin-alert').html('Invalid email or password!');
            $('.signin-alert').show();
        }
    
    }).on('ajax:error', '#vendor_log_in_form', function(e, data, status, xhr) {
       
        msg = 'Invalid email or password!';

        if (data['responseText'] == 'UserInactive'){
            msg = 'Sorry, this account is deactivated!';
        }

        $('.signin-alert').html(msg);
        $('.signin-alert').show();
        
    });
    
    $(document).ready(function(){
        
        $('#login-popup-link').click(function(){
            $('.signin-alert').html('');
            $('.signin-alert').hide();
        });
    });
    
</script>

app/views/backend/login/otp.html.erb

<div id="main_container">
    <div class="admin_login_section">
        <div class="admin_login_blk">
            <div class="logo_img"><img src="/assets/backend/logo-img.png"/></div>
            <form>
                <div class="form-group">
                    <label>Enter OTP</label>
                    <div class="form_content">
                        <input class="form-control" placeholder="9871234567" type="text">
                        <i class="fa fa-user" aria-hidden="true"></i> 
                    </div>
                </div>
                <div class="bdr_img"><img src="/assets/backend/bdr-img.jpg"/></div>
                <div class="form-group">
                    <label><strong>CHANGE PASSWORD</strong></label>
                    <div class="form-group">
                        <div class="form_content">
                            <input class="form-control" placeholder="New password" type="password">
                            <i class="fa fa-lock" aria-hidden="true"></i> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form_content">
                            <input class="form-control" placeholder="Confirm password" type="password">
                            <i class="fa fa-lock" aria-hidden="true"></i> 
                        </div>
                    </div>
                </div>
                <div class="form-group">
                  <input type="submit" value="Update Password">
                </div>
            </form>
        </div>
    </div>
</div>