config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)
  

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  devise_for :vendors, controllers: {sessions: 'vendors/sessions'}
  
  root 'welcome#index'
  get 'about-us' => 'welcome#about_us', as: "about_us"
  get 'contact-us' => 'welcome#contact_us', as: "contact_us"
  get 'work-with-us' => 'vendor_requests#new', as: "create_vendor_request"
  post 'work-with-us' => 'vendor_requests#create', as: "save_vendor_request"
  get 'hotel-detail/:id' => 'rooms#hotels_detail', as: "hotels_detail"
  get 'search-listing' => 'rooms#search_listing', as: "search_listing"
  get 'account-setting' => 'users#account_setting', as: "account_setting"
  post 'account-setting' => 'users#update_profile', as: "update_profile"
  get 'booking-history' => 'users#booking_history', as: "booking_history"
  get 'confirm-booking/:id' => 'rooms#confirm_booking', as: "confirm_booking"
  post 'save_like'               => 'rooms#save_like', as: 'save_like' 
  post 'check_save_like'         => 'rooms#check_save_like', as: 'check_save_like' 
  post 'review_submit'         => 'rooms#review_submit', as: 'review_submit' 
  post 'discount_offers'         => 'rooms#discount_offers', as: 'discount_offers' 
  post 'booking'         => 'rooms#booking', as: 'booking' 
  post 'check_availability'         => 'rooms#check_availability', as: 'check_availability' 
   
 

  namespace :backend do
    get 'dashboard' => 'dashboard#index', as: "dashboard"
    get 'login' => 'login#login', as: "login"
    get 'overview' => 'dashboard#overview', as: "overview"
    get 'booking' => 'dashboard#booking', as: "booking"
    get 'check-in' => 'dashboard#check_in', as: "check_in"
    get 'check-out' => 'dashboard#check_out', as: "check_out"
    get 'room-list' => 'dashboard#roomlist', as: "roomlist"
    get 'account-setting' => 'dashboard#account_setting', as: "account_setting"
    get 'forgot-password' => 'login#forgot_password', as: "forgot_password"
    get 'otp' => 'login#otp', as: "otp"
  end

  namespace :user do
    get 'dashboard' => 'dashboard#index', as: "dashboard"
  end  

  namespace :admin do
    get 'accept_vendor_request' => 'vendor_requests#accept_vendor_request'
    get 'reject_vendor_request' => 'vendor_requests#reject_vendor_request'
  end

end

app/controllers/backend/base_controller.rb
class Backend::BaseController < ApplicationController
	
	
end

app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < Backend::BaseController
	before_action :authenticate_vendor!

	layout 'backend'
	
	def index
		
				
	end
    
	def overview
		
				
	end
	def booking
		
				
	end
	def check_in
		
				
	end
	def check_out
		
				
	end
	def roomlist
		
				
	end
	def account_setting
		
				
	end
	
end

app/controllers/backend/login_controller.rb
class Backend::LoginController < Backend::BaseController

    layout 'backend_login'
	def login
        
	end
	def otp
        
	end
	def forgot_password
        
	end
	
end

app/views/backend/elements/_header.html.erb
<header class="fix-header">
    <div class="hidden-xs">
        <div class="logo-sect"> <a href="<%= backend_dashboard_path %>"><img src="/assets/backend/logo.png" alt=""></a> </div>
        <div class="slide-arrow">&nbsp;</div>
        <div class="pull-right right-options">
        <% if vendor_signed_in? %>
            <div class="dropdown user-dp">
                <button class="" type="button" data-toggle="dropdown"><img src="/assets/backend/user-image.png" width="21" height="21" alt=""> <em>Hi, <%= current_vendor.first_name %></em> <i class="fa fa-fw" aria-hidden="true" title="Copy to use angle-down"></i></button>
                <ul class="dropdown-menu">
                    <li><a href="#">Menu-1</a></li>
                    <li><a href="#">Menu-2</a></li>

                    <li><a href="#">Menu-2</a></li>
                </ul>
            </div>
            <div class="user-pogin-icon">
                <ul>
                    <li><a class="top-icon-user user-1" href="#">&nbsp;</a></li>
                    <li><%= link_to('<i class="top-icon-user user-2"></i>'.html_safe, destroy_vendor_session_path, :method => :get) %></li>
                </ul>
            </div>
        <% end %>
        </div>
    </div>
    <div class="hidden-sm hidden-md hidden-lg">
        <div class="slide-arrow mob-">&nbsp;</div>
        <div class="logo-sect"> <a href="dashboard.html"><img src="/assets/backend/logo.png" alt=""></a> </div>
        <div class="build-arrow"><img src="/assets/backend/build-icon.png" alt="" width="40"></div>
    
        <!--mobile-men-->
        <div class="main-mobile-menu">
            <ul>
                <li><a href="overview.html">OVERVIEW</a></li>
    
                <li>
                    <div class="chekc-in">
                        <span>
                         <a href="#"><img src="/assets/backend/check-in.png" width="25px" alt=""> CHECK - IN</a>
                        </span>
                        <span>
                        <a href="#">CHECK - OUT <img src="/assets/backend/check-out.png" alt=""></a> 
                        </span>
                    </div>
                </li>
    
                <li>
                    <div class="biicosn">
                        <img src="/assets/backend/long-team.png" alt="">
                        <i>long-term</i>
                    </div>
    
                    <div class="sub-meus">
                        <a href="roomslt.html">PRIVATE</a>
                        <a href="#">SHARED</a>
                    </div>
    
                </li>
    
                <li class="reg-li">    
                    <div class="sub-meus">
                        <a href="#">PRIVATE</a>
                        <a href="#">SHARED</a>
                    </div>
    
                    <div class="biicosn">
                        <img src="/assets/backend/regurlar.png" alt="">
                        <i>REGULAR</i>
                    </div>
                </li>
    
                <li class="sign-out"><a href="#">SIGN OUT</a></li>
    
            </ul>
        </div>
        <!--mobile-men-->
    
        <!--mobile-building-->
        <div class="main-hotel-sec">
            <ul>
                <li>SELECT HOTEL CHAIN</li>
                <li class="drop-dwon">
                    <select>
                        <option>GREATER NOIDA</option>
                        <option>GREATER NOIDA</option>
                        <option>GREATER NOIDA</option>
                        <option>GREATER NOIDA</option>
                    </select>
                </li>
            </ul>
        </div>
        <!--mobile-building-->
    </div>
</header>

app/views/backend/elements/_left_panel.html.erb
<div class="side-menu-sec">
	<div class="botm-menus">
		<div class="home-section"> <b>HOME</b>
			<ul>
				<li class="side-menu-1"><%= link_to "Overview", backend_overview_path %></li>
				<li class="side-menu-2"><a href="#">Notifications</a></li>
				<li class="side-menu-3"><a href="#">Messages</a></li>
			</ul>
		</div>
		<div class="home-section"> <b>BOOKINGS</b>
			<ul>
				<li class="side-menu-4"><%= link_to "Booked", backend_booking_path %></li>
				<li class="side-menu-5"><%= link_to "Check-In", backend_check_in_path %></li>
				<li class="side-menu-6"><%= link_to "Check-Out", backend_check_out_path %></li>
			</ul>
		</div>

		<div class="home-section"> <b>ROOMS</b>
			<ul>
				<li class="side-menu-7">
					<div class="side-menu-">
						<div class="sid-accor">
							<div class="panel-heading" data-acc-link="demo1">Long-Term</div>
							<div class="panel-body" data-acc-content="demo1">
								<ul class="acor-menu">
									<li><%= link_to "Private Room", backend_roomlist_path %></li>
									<li><%= link_to "Shared Room", backend_roomlist_path %></li>
								</ul>
							</div>
						</div>
					</div>
				</li>
				<li class="side-menu-8">
					<div class="side-menu-">
						<div class="sid-accor">
							<div class="panel-heading" data-acc-link="demo2">Regular</div>
							<div class="panel-body" data-acc-content="demo2">
								<ul class="acor-menu">
									<li><a href="#">Menu-01</a></li>
									<li><a href="#">Menu-02</a></li>
									<li><a href="#">Menu-03</a></li>
									<li><a href="#">Menu-04</a></li>
								</ul>
							</div>
						</div>
					</div>
				</li>
			</ul>
		</div>
		<div class="home-section"> <b>SETTINGS</b>
			<ul>
				<li class="side-menu-9"><a href="#">Account Settings</a></li>
			</ul>
		</div>
	</div>
</div>